services:
  dvwa:
    image: cytopia/dvwa:latest
    ports:
      - "8080:80"
    environment:
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_ROOT_PASSWORD=root
      - PHPIDS_ENABLED=0
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_ROOT_PASSWORD=root
    command: --sql-mode=""
