name: SAST - Semgrep

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Если используешь Python-утилиту semgrep (CE)
      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install semgrep
          semgrep --version

      # Запуск набора правил (OWASP Top 10 + PHP/JS) и экспорт SARIF
      - name: Run Semgrep scan
        run: |
          semgrep scan \
            --config p/owasp-top-ten \
            --config p/php \
            --config p/javascript \
            --exclude node_modules --exclude vendor \
            --sarif --sarif-output semgrep.sarif \
            --error

      # Публикация отчёта в GitHub Security (отобразится в Security->Code scanning alerts)
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
