name: SAST - Semgrep

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install semgrep
          semgrep --version

      - name: Run Semgrep scan
        run: |
          semgrep scan \
            --config p/owasp-top-ten \
            --config p/php \
            --config p/javascript \
            --exclude node_modules --exclude vendor \
            --output semgrep-report.md \
            --error

      # 🟢 Новый шаг: сохранить файл semgrep-report.md
      - name: Upload Semgrep report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.md
